// <auto-generated />
using System;
using GraphQL.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQL.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240417120320_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQL.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e444aaf8-b4cc-43f3-9113-e13dd4c93b5f"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("4c004851-1720-4fff-8c0c-ce7863292e9d"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("81b2d133-9c69-49f6-87ff-2973d3ca737f"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("d728a4f4-665f-4fa8-97b0-3d6141c98642"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a82aa302-e2c0-4a73-a185-2eb2163c60b8"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("d728a4f4-665f-4fa8-97b0-3d6141c98642"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphQL.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c004851-1720-4fff-8c0c-ce7863292e9d"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("d728a4f4-665f-4fa8-97b0-3d6141c98642"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphQL.Domain.Entities.Account", b =>
                {
                    b.HasOne("GraphQL.Domain.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GraphQL.Domain.Entities.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
